[LangOptions]
LanguageName=فارسی
LanguageID=$0429
LanguageCodePage=65001
DialogFontName=Tahoma
DialogFontSize=9
WelcomeFontName=Tahoma
WelcomeFontSize=12
TitleFontName=Tahoma
TitleFontSize=29
CopyrightFontName=Tahoma
CopyrightFontSize=8
RightToLeft=yes

[Messages]
SetupWindowTitle=نصب %1
SetupAppTitle=نصب
SetupAppRunningError=برنامه %1 در حال اجراست.%n%nلطفاً آن را ببندید و دوباره تلاش کنید.
WelcomeLabel1=به نصب‌کننده [name] خوش آمدید
WelcomeLabel2=این برنامه [name/ver] را روی رایانه شما نصب می‌کند.%n%nپیشنهاد می‌شود پیش از ادامه، برنامه‌های دیگر را ببندید.
ClickNext=برای ادامه روی «بعدی» کلیک کنید.
SelectDirDesc=محل نصب برنامه را انتخاب کنید.
SelectDirLabel3=نصب‌کننده، [name] را در پوشه زیر نصب می‌کند.
ReadyLabel1=نصب‌کننده آماده نصب [name] است.
ReadyLabel2a=برای شروع نصب روی «نصب» کلیک کنید؛ برای بازبینی تنظیمات «برگشت» را بزنید.
InstallingLabel=لطفاً تا پایان نصب [name] منتظر بمانید.
FinishedHeadingLabel=نصب [name] کامل شد
FinishedLabelNoIcons=برنامه [name] روی رایانه شما نصب شد.
FinishedLabel=برنامه [name] روی رایانه شما نصب شد. برای اجرا از میانبر ایجادشده استفاده کنید.
ClickFinish=برای بستن نصب‌کننده روی «پایان» کلیک کنید.
StatusExtractFiles=در حال استخراج فایل‌ها...
StatusCreateIcons=در حال ساخت میانبرها...
StatusRunProgram=در حال پایان نصب...
StatusRollback=در حال بازگردانی تغییرات...
ErrorChangingAttr=تغییر ویژگی‌های فایل انجام نشد.
ErrorCreatingDir=ساخت پوشه انجام نشد.
ErrorTooManyFilesInDir=تعداد فایل‌های پوشه بیش از حد مجاز است.
ButtonBack=< برگشت
ButtonNext=بعدی >
ButtonInstall=نصب
ButtonOK=تأیید
ButtonCancel=انصراف
ButtonYes=بله
ButtonYesToAll=بله برای همه
ButtonNo=خیر
ButtonNoToAll=خیر برای همه
ButtonFinish=پایان
ButtonBrowse=انتخاب...
ButtonWizardBrowse=انتخاب...
ButtonNewFolder=پوشه جدید
SelectTasksDesc=گزینه‌های دلخواه را انتخاب کنید.
SelectTasksLabel2=مواردی را که می‌خواهید نصب‌کننده انجام دهد انتخاب کنید و سپس «بعدی» را بزنید.
PreparingDesc=نصب‌کننده در حال آماده‌سازی است.
PreparingLabel1=در حال آماده‌سازی نصب [name]
UninstallAppFullTitle=حذف %1
UninstallAppTitle=حذف
UninstallingLabel=لطفاً تا پایان حذف %1 منتظر بمانید.
UninstalledAll=برنامه %1 با موفقیت حذف شد.
UninstalledMost=حذف %1 کامل شد.%n%nبرخی موارد به‌صورت دستی باید پاک شوند.
